FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --only-binary=pillow pillow && \
    pip install --no-cache-dir -r requirements.txt --no-deps

# Создаем директории для временных файлов и шрифтов
RUN mkdir -p temp fonts

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 